theme = "gruvbox_light_soft"

[editor]
# Show currently open buffers, only when more than one exists.
bufferline = "multiple"
# Highlight all lines with a cursor
cursorline = true
# Use relative line numbers
line-number = "relative"
# Show a ruler at column 120
rulers = [120]
# Force the theme to show colors
true-color = true
color-modes = true
trim-trailing-whitespace = true
completion-replace = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "â•Ž"
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
"C-c"= ["collapse_selection", "normal_mode"]
# home/end replacement (added to both insert/normal):
"C-e" = ["goto_line_end", "move_char_right"]
"C-a" = "goto_line_start"

[keys.normal]
X = "select_line_above"
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
0   = "goto_line_start"
"^" = "goto_first_nonwhitespace"
H = "goto_first_nonwhitespace"
"$" = "goto_line_end"
L = "goto_line_end"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
"C-/" = "toggle_comments"
"C-c" = "copy_selection_on_next_line"

[keys.select]
X = "select_line_above"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"C-c" = ["collapse_selection", "keep_primary_selection", "normal_mode"]
0   = "goto_line_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
"#" = "toggle_comments"
p = "replace_selections_with_clipboard"
